FROM nginx

WORKDIR /home/Nginx

COPY nginx.conf /home/Nginx/nginx.conf
COPY templates /home/Nginx/templates/
COPY templates /usr/share/nginx/html/templates/
COPY static /usr/share/nginx/html/static/
COPY static /home/Nginx/static/